In [2]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [4]:
#Load Data
df = pd.read_csv('cleaneddata.csv')
df.head(10)

Condition  Cylinder heating zone 1  Cylinder heating zone 2  \
0   Normal1               288.350000               299.230000   
1   Normal1               281.620000               290.250000   
2   Normal1               285.520000               304.260000   
3   Normal1               278.513125               286.230000   
4   Normal1               273.880000               280.360000   
5   Normal1               268.110000               291.140000   
6   Normal1               272.700000               296.695208   
7   Normal1               265.850000               284.430000   
8   Normal1               288.280000               299.280000   
9   Normal1               270.150000               287.190000   

   Cylinder heating zone 3  Cylinder heating zone 4  Cylinder heating zone 5  \
0               322.160000                   295.85               314.590000   
1               296.760000                   297.53               310.640000   
2               311.490000                   302.41               320.420000   
3               320.730000                   319.29               327.560000   
4               299.980000                   299.78               304.210000   
5               309.150000                   302.24               322.930000   
6               310.539583                   322.48               313.220000   
7               321.890000                   310.26               313.630000   
8               313.050000                   317.75               316.570625   
9               324.990000                   295.15               299.870000   

   Mould temperature control unit 1  Maximum injection pressure  \
0                             89.59                 1561.720000   
1                             89.37                 1548.980000   
2                             89.96                 1419.080000   
3                             86.06                 1565.210000   
4                             89.66                 1515.130000   
5                             93.56                 1583.940000   
6                             90.92                 1545.820208   
7                             85.63                 1518.070000   
8                             87.61                 1482.730000   
9                             94.17                 1472.170000   

   Injection time  Dosage time  Cycle time  Switch-over volume  \
0        0.234000      3.13600   27.870000            1.443340   
1        0.224000      2.99800   27.548000            1.413340   
2        0.234000      2.99800   30.216000            1.443340   
3        0.234000      2.94175   28.256000            1.343340   
4        0.224000      3.11800   27.976000            1.473340   
5        0.224000      3.11000   28.816000            1.405215   
6        0.224000      2.98800   28.800958            1.393340   
7        0.224000      2.95000   27.518000            1.403340   
8        0.224000      3.05600   29.678000            1.403340   
9        0.233167      2.80600   29.008000            1.483340   

   Material cushion  
0          0.918447  
1          0.929772  
2          0.899388  
3          0.996952  
4          0.929580  
5          0.912977  
6          0.953863  
7          0.965242  
8          0.922977  
9          0.914110

In [6]:
#Summarize of Data
df.describe().transpose()

count         mean        std          min  \
Cylinder heating zone 1           116.0   281.019283   9.198632   265.850000   
Cylinder heating zone 2           116.0   298.033796   9.816407   280.360000   
Cylinder heating zone 3           116.0   312.661764  10.262570   294.710000   
Cylinder heating zone 4           116.0   311.684035   9.772969   294.750000   
Cylinder heating zone 5           116.0   318.128118   9.028320   299.870000   
Mould temperature control unit 1  116.0    89.985427   2.375933    85.630000   
Maximum injection pressure        116.0  1530.529502  49.458811  1419.080000   
Injection time                    116.0     0.232311   0.008098     0.218000   
Dosage time                       116.0     2.907734   0.093539     2.706000   
Cycle time                        116.0    28.779633   0.832908    27.418000   
Switch-over volume                116.0     1.463218   0.083363     1.343340   
Material cushion                  116.0     0.979066   0.061471     0.868255   

                                          25%          50%          75%  \
Cylinder heating zone 1            273.255000   280.650000   288.287500   
Cylinder heating zone 2            290.165000   299.345000   306.142500   
Cylinder heating zone 3            304.697500   311.645000   321.930417   
Cylinder heating zone 4            302.462500   313.230000   319.167500   
Cylinder heating zone 5            312.525000   317.905000   325.434167   
Mould temperature control unit 1    88.237500    90.125000    91.492500   
Maximum injection pressure        1487.725000  1533.205000  1566.557500   
Injection time                       0.224000     0.234000     0.238000   
Dosage time                          2.840500     2.909000     2.970000   
Cycle time                          28.024500    28.790000    29.490500   
Switch-over volume                   1.393340     1.443340     1.535100   
Material cushion                     0.930766     0.966001     1.027220   

                                         max  
Cylinder heating zone 1            303.87000  
Cylinder heating zone 2            320.00000  
Cylinder heating zone 3            335.46000  
Cylinder heating zone 4            334.03000  
Cylinder heating zone 5            340.96000  
Mould temperature control unit 1    94.37000  
Maximum injection pressure        1636.00000  
Injection time                       0.24400  
Dosage time                          3.13600  
Cycle time                          30.30200  
Switch-over volume                   1.63510  
Material cushion                     1.13039

In [12]:
#Normalize Data Predictors (Zero-score normalization)
target_column = ['Condition']
predictors = list(set(list(df.columns))-set(target_column))
df[predictors] = df[predictors]/df[predictors].max()
df[0:10]

Condition  Cylinder heating zone 1  Cylinder heating zone 2  \
0   Normal1                 0.948926                 0.935094   
1   Normal1                 0.926778                 0.907031   
2   Normal1                 0.939612                 0.950812   
3   Normal1                 0.916554                 0.894469   
4   Normal1                 0.901306                 0.876125   
5   Normal1                 0.882318                 0.909812   
6   Normal1                 0.897423                 0.927173   
7   Normal1                 0.874881                 0.888844   
8   Normal1                 0.948695                 0.935250   
9   Normal1                 0.889031                 0.897469   

   Cylinder heating zone 3  Cylinder heating zone 4  Cylinder heating zone 5  \
0                 0.960353                 0.885699                 0.922660   
1                 0.884636                 0.890728                 0.911075   
2                 0.928546                 0.905338                 0.939758   
3                 0.956090                 0.955872                 0.960699   
4                 0.894235                 0.897464                 0.892216   
5                 0.921570                 0.904829                 0.947120   
6                 0.925713                 0.965422                 0.918641   
7                 0.959548                 0.928839                 0.919844   
8                 0.933196                 0.951262                 0.928469   
9                 0.968789                 0.883603                 0.879487   

   Mould temperature control unit 1  Maximum injection pressure  \
0                          0.949348                    0.954597   
1                          0.947017                    0.946809   
2                          0.953269                    0.867408   
3                          0.911942                    0.956730   
4                          0.950090                    0.926119   
5                          0.991417                    0.968178   
6                          0.963442                    0.944878   
7                          0.907386                    0.927916   
8                          0.928367                    0.906314   
9                          0.997881                    0.899859   

   Injection time  Dosage time  Cycle time  Switch-over volume  \
0        0.959016     1.000000    0.919741            0.882723   
1        0.918033     0.955995    0.909115            0.864375   
2        0.959016     0.955995    0.997162            0.882723   
3        0.959016     0.938058    0.932480            0.821564   
4        0.918033     0.994260    0.923239            0.901070   
5        0.918033     0.991709    0.950960            0.859406   
6        0.918033     0.952806    0.950464            0.852144   
7        0.918033     0.940689    0.908125            0.858259   
8        0.918033     0.974490    0.979407            0.858259   
9        0.955601     0.894770    0.957297            0.907186   

   Material cushion  
0          0.812505  
1          0.822523  
2          0.795644  
3          0.881954  
4          0.822353  
5          0.807665  
6          0.843836  
7          0.853902  
8          0.816512  
9          0.808668

In [14]:
#Create Training and Testing Datasets
# Assuming predictors and target_column are already defined
X = df[predictors].values
y = df[target_column].values

# Splitting data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Checking the shapes of the resulting splits
print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

Training data shape: (81, 12)
Testing data shape: (35, 12)


In [26]:
#Build Neural Network Model
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

# Build the neural network model with 3 hidden layers, each with 10 neurons
mlp = MLPClassifier(
    hidden_layer_sizes=(20, 20, 20),    # 3 hidden layers, each with 10 neurons
    activation='relu',                  # ReLU activation function
    solver='adam',                      # Adam optimizer
    max_iter=1000,                      # Maximum iterations for training
    random_state=42,                     # For reproducibility
    learning_rate_init=0.001
)

# Train the model
mlp.fit(X_train, y_train)

# Predict on the test set
y_pred = mlp.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy of the Neural Network model:", accuracy)

C:\Users\Jason\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1101: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy of the Neural Network model: 0.9714285714285714


C:\Users\Jason\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [28]:
#Evaluate MLP Model
from sklearn.metrics import classification_report,confusion_matrix
predict_train = mlp.predict(X_train)
print("MLP confusion_matrix", "\n", confusion_matrix(y_train,predict_train))
print("\n")
print("MLP classification report", "\n", classification_report(y_train,predict_train))


MLP confusion_matrix 
 [[18  0  2]
 [ 0 28  0]
 [ 1  0 32]]


MLP classification report 
               precision    recall  f1-score   support

  Condition1       0.95      0.90      0.92        20
  Condition3       1.00      1.00      1.00        28
     Normal1       0.94      0.97      0.96        33

    accuracy                           0.96        81
   macro avg       0.96      0.96      0.96        81
weighted avg       0.96      0.96      0.96        81



In [30]:
#Evaluate Prediction Result
predict_test = mlp.predict(X_test)
print("MLP Prediction confusion_matrix", "\n", confusion_matrix(y_test,predict_test))
print("\n")
print("MLP Prediction classification report", "\n",
classification_report(y_test,predict_test))

MLP Prediction confusion_matrix 
 [[ 5  0  1]
 [ 0 12  0]
 [ 0  0 17]]


MLP Prediction classification report 
               precision    recall  f1-score   support

  Condition1       1.00      0.83      0.91         6
  Condition3       1.00      1.00      1.00        12
     Normal1       0.94      1.00      0.97        17

    accuracy                           0.97        35
   macro avg       0.98      0.94      0.96        35
weighted avg       0.97      0.97      0.97        35

